[package]
name = "playing-with-rust"
version = "0.1.0"
authors = ["Chelo84 <marcelo_lacroix@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.0"